#!/usr/bin/env bash
# Cross-compile Dino's non-UI dependency stack for iOS.
#
# Usage: ./build-deps.sh [sim-arm64|device-arm64] [dep ...]
#        With no dep arguments, builds everything in order.
#
# Everything is built as static libraries into ios/prefix/<target>.
set -euo pipefail

TARGET="${1:-sim-arm64}"
shift || true

ROOT="$(cd "$(dirname "$0")" && pwd)"
DEPS="$ROOT/deps"
PREFIX="$ROOT/prefix/$TARGET"
CROSS="$ROOT/cross/$TARGET.ini"
NCPU="$(sysctl -n hw.ncpu)"
MIN_IOS=16.0

GLIB_VER=2.84
GLIB_PATCH=4
GEE_VER=0.20
GEE_PATCH=8
PIXBUF_VER=2.42
PIXBUF_PATCH=12
OPENSSL_VER=3.5.1
GLIB_NETWORKING_VER=2.80
GLIB_NETWORKING_PATCH=1
GPGERROR_VER=1.55
GCRYPT_VER=1.11.2
OMEMO_C_VER=0.5.1
PROTOBUF_C_VER=1.5.2
SRTP_VER=2.7.0
PSL_VER=0.21.5
SOUP_VER=3.6
SOUP_PATCH=5

case "$TARGET" in
  sim-arm64)
    SDK=iphonesimulator
    TRIPLE="arm64-apple-ios${MIN_IOS}-simulator"
    SUBSYSTEM=ios-simulator
    OPENSSL_TARGET=iossimulator-arm64-xcrun
    OPENSSL_MIN_FLAG="-mios-simulator-version-min=$MIN_IOS"
    ;;
  device-arm64)
    SDK=iphoneos
    TRIPLE="arm64-apple-ios${MIN_IOS}"
    SUBSYSTEM=ios
    OPENSSL_TARGET=ios64-xcrun
    OPENSSL_MIN_FLAG="-mios-version-min=$MIN_IOS"
    ;;
  *) echo "unknown target $TARGET" >&2; exit 1 ;;
esac

SDKPATH="$(xcrun --sdk "$SDK" --show-sdk-path)"
CLANG="$(xcrun --sdk "$SDK" -f clang)"
CLANGXX="$(xcrun --sdk "$SDK" -f clang++)"
AR="$(xcrun --sdk "$SDK" -f ar)"
STRIP="$(xcrun --sdk "$SDK" -f strip)"
VALAC="$(command -v valac)"
MESON="$(command -v meson)"

mkdir -p "$DEPS" "$PREFIX" "$ROOT/cross"

cat > "$CROSS" <<EOF
# Generated by build-deps.sh for $TARGET — do not edit, regenerate instead.
[host_machine]
system = 'darwin'
subsystem = '$SUBSYSTEM'
kernel = 'xnu'
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'

[binaries]
c = '$CLANG'
cpp = '$CLANGXX'
objc = '$CLANG'
objcpp = '$CLANGXX'
ar = '$AR'
strip = '$STRIP'
vala = '$VALAC'
pkg-config = '$(command -v pkg-config)'

[built-in options]
c_args = ['-target', '$TRIPLE', '-isysroot', '$SDKPATH', '-I$PREFIX/include', '-include', '$ROOT/compat/ios-compat.h']
c_link_args = ['-target', '$TRIPLE', '-isysroot', '$SDKPATH', '-L$PREFIX/lib']
cpp_args = ['-target', '$TRIPLE', '-isysroot', '$SDKPATH', '-I$PREFIX/include']
cpp_link_args = ['-target', '$TRIPLE', '-isysroot', '$SDKPATH', '-L$PREFIX/lib']
objc_args = ['-target', '$TRIPLE', '-isysroot', '$SDKPATH']
objc_link_args = ['-target', '$TRIPLE', '-isysroot', '$SDKPATH']

[properties]
needs_exe_wrapper = true
pkg_config_libdir = ['$PREFIX/lib/pkgconfig', '$PREFIX/share/pkgconfig']
EOF
echo "wrote $CROSS"

# sqlite comes from the iOS SDK (libsqlite3.tbd); give pkg-config something
# to find.
mkdir -p "$PREFIX/lib/pkgconfig"
SQLITE_VER_DETECTED="$(grep -m1 '#define SQLITE_VERSION ' "$SDKPATH/usr/include/sqlite3.h" | sed 's/.*"\(.*\)".*/\1/')"
cat > "$PREFIX/lib/pkgconfig/sqlite3.pc" <<EOF2
Name: SQLite
Description: SQLite from the iOS SDK (libsqlite3.tbd + sqlite3.h)
Version: ${SQLITE_VER_DETECTED:-3.43.0}
Libs: -lsqlite3
Cflags:
EOF2

fetch() { # fetch <url> <dirname>
  local url="$1" dir="$2"
  if [ ! -d "$DEPS/$dir" ]; then
    echo "downloading $url"
    curl -fsSL "$url" -o "$DEPS/$dir.tar.xz.tmp"
    mkdir -p "$DEPS/$dir"
    tar -xf "$DEPS/$dir.tar.xz.tmp" -C "$DEPS/$dir" --strip-components=1
    rm "$DEPS/$dir.tar.xz.tmp"
  fi
}

meson_build() { # meson_build <srcdir> [extra meson args...]
  local src="$1"; shift
  local bdir="$src/_build-$TARGET"
  rm -rf "$bdir"
  "$MESON" setup "$bdir" "$src" --cross-file "$CROSS" --prefix "$PREFIX" \
    --default-library static --buildtype release "$@"
  ninja -C "$bdir" -j "$NCPU"
  ninja -C "$bdir" install
}

build_glib() {
  fetch "https://download.gnome.org/sources/glib/$GLIB_VER/glib-$GLIB_VER.$GLIB_PATCH.tar.xz" "glib"
  meson_build "$DEPS/glib" \
    -Dtests=false -Dintrospection=disabled -Ddocumentation=false \
    -Dman-pages=disabled -Dnls=enabled -Dlibmount=disabled -Dselinux=disabled \
    -Ddtrace=disabled -Dsystemtap=disabled -Dglib_debug=disabled \
    -Dpcre2:jit=disabled
}

build_gee() {
  fetch "https://download.gnome.org/sources/libgee/$GEE_VER/libgee-$GEE_VER.$GEE_PATCH.tar.xz" "libgee"
  cd "$DEPS/libgee"
  make distclean >/dev/null 2>&1 || true
  PKG_CONFIG_LIBDIR="$PREFIX/lib/pkgconfig:$PREFIX/share/pkgconfig" \
  CC="$CLANG -target $TRIPLE -isysroot $SDKPATH" \
  VALAC="$VALAC" \
  ./configure --host=aarch64-apple-darwin --prefix="$PREFIX" \
    --disable-shared --enable-static --enable-introspection=no
  make -j "$NCPU"
  make install
  cd -
}

build_pixbuf() {
  fetch "https://download.gnome.org/sources/gdk-pixbuf/$PIXBUF_VER/gdk-pixbuf-$PIXBUF_VER.$PIXBUF_PATCH.tar.xz" "gdk-pixbuf"
  (cd "$DEPS/gdk-pixbuf" && "$MESON" wrap install libpng 2>/dev/null || true)
  meson_build "$DEPS/gdk-pixbuf" \
    -Dpng=enabled -Djpeg=disabled -Dtiff=disabled -Dgif=enabled \
    -Dothers=disabled -Dbuiltin_loaders=all -Dgio_sniffing=false \
    -Dman=false -Dtests=false -Dinstalled_tests=false -Dintrospection=disabled
}

build_openssl() {
  fetch "https://github.com/openssl/openssl/releases/download/openssl-$OPENSSL_VER/openssl-$OPENSSL_VER.tar.gz" "openssl"
  cd "$DEPS/openssl"
  make distclean >/dev/null 2>&1 || true
  ./Configure "$OPENSSL_TARGET" no-shared no-tests no-apps no-docs \
    "$OPENSSL_MIN_FLAG" --prefix="$PREFIX" --libdir=lib
  make -j "$NCPU" build_libs
  make install_dev
  cd -
}

build_glib_networking() {
  fetch "https://download.gnome.org/sources/glib-networking/$GLIB_NETWORKING_VER/glib-networking-$GLIB_NETWORKING_VER.$GLIB_NETWORKING_PATCH.tar.xz" "glib-networking"
  meson_build "$DEPS/glib-networking" \
    -Dgnutls=disabled -Dopenssl=enabled -Dlibproxy=disabled \
    -Dgnome_proxy=disabled -Dinstalled_tests=false -Ddebug_logs=false
}

autotools_build() { # autotools_build <srcdir> [extra configure args...]
  local src="$1"; shift
  cd "$src"
  make distclean >/dev/null 2>&1 || true
  PKG_CONFIG_LIBDIR="$PREFIX/lib/pkgconfig:$PREFIX/share/pkgconfig" \
  CC="$CLANG -target $TRIPLE -isysroot $SDKPATH -include $ROOT/compat/ios-compat.h" \
  CXX="$CLANGXX -target $TRIPLE -isysroot $SDKPATH" \
  ./configure --host=aarch64-apple-darwin --prefix="$PREFIX" \
    --disable-shared --enable-static "$@"
  make -j "$NCPU"
  make install
  cd -
}

build_gpgerror() {
  fetch "https://www.gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-$GPGERROR_VER.tar.bz2" "libgpg-error"
  autotools_build "$DEPS/libgpg-error" --disable-doc --disable-tests --disable-nls \
    --enable-install-gpg-error-config
}

build_gcrypt() {
  fetch "https://www.gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-$GCRYPT_VER.tar.bz2" "libgcrypt"
  autotools_build "$DEPS/libgcrypt" --disable-doc --disable-asm \
    --with-libgpg-error-prefix="$PREFIX"
}

build_protobuf_c() {
  fetch "https://github.com/protobuf-c/protobuf-c/releases/download/v$PROTOBUF_C_VER/protobuf-c-$PROTOBUF_C_VER.tar.gz" "protobuf-c"
  autotools_build "$DEPS/protobuf-c" --disable-protoc
}

build_omemo_c() {
  fetch "https://github.com/dino/libomemo-c/archive/refs/tags/v$OMEMO_C_VER.tar.gz" "libomemo-c"
  cmake -S "$DEPS/libomemo-c" -B "$DEPS/libomemo-c/_build-$TARGET" \
    -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_SYSROOT="$SDKPATH" \
    -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_OSX_DEPLOYMENT_TARGET=$MIN_IOS \
    -DCMAKE_INSTALL_PREFIX="$PREFIX" -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=OFF -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
    -DCMAKE_C_FLAGS="-I$PREFIX/include" \
    -DCMAKE_EXE_LINKER_FLAGS="-L$PREFIX/lib" \
    -DCMAKE_FIND_ROOT_PATH="$PREFIX"
  cmake --build "$DEPS/libomemo-c/_build-$TARGET" -j "$NCPU"
  cmake --install "$DEPS/libomemo-c/_build-$TARGET"
}

build_srtp() {
  fetch "https://github.com/cisco/libsrtp/archive/refs/tags/v$SRTP_VER.tar.gz" "libsrtp"
  meson_build "$DEPS/libsrtp" -Dtests=disabled
}

build_psl() {
  fetch "https://github.com/rockdaboot/libpsl/releases/download/$PSL_VER/libpsl-$PSL_VER.tar.gz" "libpsl"
  meson_build "$DEPS/libpsl" -Druntime=no -Dtests=false -Ddocs=false
}

build_soup() {
  fetch "https://download.gnome.org/sources/libsoup/$SOUP_VER/libsoup-$SOUP_VER.$SOUP_PATCH.tar.xz" "libsoup"
  (cd "$DEPS/libsoup" && "$MESON" wrap install nghttp2 2>/dev/null || true)
  meson_build "$DEPS/libsoup" \
    -Dtests=false -Ddocs=disabled -Dintrospection=disabled -Dvapi=disabled \
    -Dgssapi=disabled -Dbrotli=disabled -Dntlm=disabled -Dtls_check=false \
    -Dsysprof=disabled -Dautobahn=disabled -Dpkcs11_tests=disabled
}

if [ $# -eq 0 ]; then
  set -- glib gee pixbuf openssl glib_networking gpgerror gcrypt protobuf_c omemo_c srtp psl soup
fi
for dep in "$@"; do
  echo "=== building $dep ($TARGET) ==="
  "build_$dep"
done
echo "=== done: $PREFIX ==="
